-- Supabase schema for AI Website Builder landing page

create extension if not exists "pgcrypto";

create table if not exists public.course_leads (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  phone text not null,
  email text,
  learning_goal text,
  note text,
  source text default 'landing_page',
  created_at timestamptz not null default now()
);

alter table public.course_leads enable row level security;

-- Allow public users to submit lead form
drop policy if exists "Allow public insert course leads" on public.course_leads;
create policy "Allow public insert course leads"
on public.course_leads
for insert
to anon
with check (
  full_name is not null
  and phone is not null
);

-- Do not create public select/update/delete policies.
-- Leads should only be viewed from Supabase dashboard or a protected admin system later.

create index if not exists course_leads_created_at_idx
on public.course_leads (created_at desc);

-- ============================================================
-- Thanh toán tự động qua SePay (chuyển khoản ngân hàng + webhook)
-- ============================================================

-- Đơn hàng mua khóa học. Chỉ đọc/ghi qua service role key ở phía server
-- (API routes) — KHÔNG tạo policy public cho bảng này.
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  -- Số đơn hàng thân thiện để hiển thị (vd #1024)
  order_number bigint generated by default as identity (start with 1000) unique,
  plan_id text not null,
  plan_name text not null,
  -- Số tiền VND
  amount bigint not null check (amount > 0),
  -- Mã chuyển khoản duy nhất (vd AWB7K2M4Q) — khách ghi vào nội dung CK
  transfer_code text not null unique,
  status text not null default 'pending' check (status in ('pending', 'paid', 'expired')),
  full_name text not null,
  phone text not null,
  email text,
  -- Lead tương ứng trong course_leads (nếu tạo được)
  lead_id uuid references public.course_leads (id),
  -- Thông tin giao dịch SePay khi đã thanh toán
  sepay_transaction_id bigint,
  sepay_reference_code text,
  paid_amount bigint,
  paid_at timestamptz,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;
-- Không tạo policy public — mọi truy cập đi qua service role ở server.

create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_created_at_idx on public.orders (created_at desc);

-- Nhật ký mọi giao dịch SePay gửi về webhook — phục vụ đối soát/audit.
create table if not exists public.sepay_transactions (
  id uuid primary key default gen_random_uuid(),
  -- ID giao dịch phía SePay (chống ghi trùng khi webhook retry)
  sepay_id bigint not null unique,
  gateway text,
  transaction_date text,
  account_number text,
  sub_account text,
  code text,
  content text,
  transfer_type text,
  transfer_amount bigint,
  accumulated bigint,
  reference_code text,
  description text,
  -- Đơn hàng khớp được (nếu có)
  order_id uuid references public.orders (id),
  created_at timestamptz not null default now()
);

alter table public.sepay_transactions enable row level security;
-- Không tạo policy public — chỉ webhook (service role) được ghi.

-- ============================================================
-- Admin Settings
-- ============================================================

-- Cài đặt admin (API keys, webhook URLs)
create table if not exists public.admin_settings (
  id text primary key default '1',
  sepay_api_key text,
  sepay_webhook_url text,
  bank_account_number text,
  bank_account_name text,
  bank_code text,
  updated_at timestamptz not null default now()
);

alter table public.admin_settings enable row level security;
-- Không tạo policy public — chỉ authenticated admin được truy cập.

-- ============================================================
-- Tài khoản học viên — tự cấp khi thanh toán thành công
-- ============================================================

-- Mỗi đơn đã thanh toán tạo (hoặc nâng cấp) một tài khoản học viên. Đăng nhập
-- bằng email + mật khẩu; chỉ đọc/ghi qua service role ở server (KHÔNG policy public).
-- Chỉ lưu HASH mật khẩu (scrypt), không bao giờ lưu mật khẩu gốc.
create table if not exists public.student_accounts (
  id uuid primary key default gen_random_uuid(),
  -- Đơn hàng đã kích hoạt tài khoản (unique để webhook retry không tạo trùng)
  order_id uuid unique references public.orders (id),
  email text not null,
  full_name text not null,
  phone text,
  plan_id text not null,
  plan_name text,
  -- Định dạng: scrypt$N$r$p$saltB64$hashB64
  password_hash text not null,
  -- Mật khẩu tạm dạng phẳng để admin xem/gửi tay khi email chưa gửi được.
  -- Chỉ đọc qua service role ở server; xóa (null) ngay khi học viên tự đổi mật khẩu.
  temp_password text,
  -- true khi vẫn dùng mật khẩu tạm hệ thống cấp (khuyến khích đổi)
  must_change_password boolean not null default true,
  status text not null default 'active' check (status in ('active', 'disabled')),
  -- Trạng thái gửi email cấp tài khoản để đối soát khi email lỗi
  welcome_email_status text not null default 'pending'
    check (welcome_email_status in ('pending', 'sent', 'failed', 'skipped')),
  welcome_email_error text,
  welcome_email_sent_at timestamptz,
  last_login_at timestamptz,
  -- Mốc đổi/đặt lại mật khẩu — session cấp trước mốc này bị vô hiệu hóa.
  password_changed_at timestamptz,
  created_at timestamptz not null default now()
);

-- Migration bổ sung (chạy lại nhiều lần an toàn): cột mật khẩu tạm để admin
-- xem/cấp lại cho DB đã tạo trước khi có tính năng này.
alter table public.student_accounts
  add column if not exists temp_password text;

alter table public.student_accounts enable row level security;
-- Không tạo policy public — mọi truy cập đi qua service role ở server.

-- Email là định danh đăng nhập → duy nhất, không phân biệt hoa thường.
create unique index if not exists student_accounts_email_key
on public.student_accounts (lower(email));

create index if not exists student_accounts_created_at_idx
on public.student_accounts (created_at desc);
