-- Supabase schema for AI Website Builder landing page

create extension if not exists "pgcrypto";

create table if not exists public.course_leads (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  phone text not null,
  email text,
  learning_goal text,
  note text,
  source text default 'landing_page',
  created_at timestamptz not null default now()
);

alter table public.course_leads enable row level security;

-- Allow public users to submit lead form
create policy "Allow public insert course leads"
on public.course_leads
for insert
to anon
with check (
  full_name is not null
  and phone is not null
);

-- Do not create public select/update/delete policies.
-- Leads should only be viewed from Supabase dashboard or a protected admin system later.

create index if not exists course_leads_created_at_idx
on public.course_leads (created_at desc);

-- ============================================================
-- Thanh toán tự động qua SePay (chuyển khoản ngân hàng + webhook)
-- ============================================================

-- Đơn hàng mua khóa học. Chỉ đọc/ghi qua service role key ở phía server
-- (API routes) — KHÔNG tạo policy public cho bảng này.
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  -- Số đơn hàng thân thiện để hiển thị (vd #1024)
  order_number bigint generated by default as identity (start with 1000) unique,
  plan_id text not null,
  plan_name text not null,
  -- Số tiền VND
  amount bigint not null check (amount > 0),
  -- Mã chuyển khoản duy nhất (vd AWB7K2M4Q) — khách ghi vào nội dung CK
  transfer_code text not null unique,
  status text not null default 'pending' check (status in ('pending', 'paid', 'expired')),
  full_name text not null,
  phone text not null,
  email text,
  -- Lead tương ứng trong course_leads (nếu tạo được)
  lead_id uuid references public.course_leads (id),
  -- Thông tin giao dịch SePay khi đã thanh toán
  sepay_transaction_id bigint,
  sepay_reference_code text,
  paid_amount bigint,
  paid_at timestamptz,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;
-- Không tạo policy public — mọi truy cập đi qua service role ở server.

create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_created_at_idx on public.orders (created_at desc);

-- Nhật ký mọi giao dịch SePay gửi về webhook — phục vụ đối soát/audit.
create table if not exists public.sepay_transactions (
  id uuid primary key default gen_random_uuid(),
  -- ID giao dịch phía SePay (chống ghi trùng khi webhook retry)
  sepay_id bigint not null unique,
  gateway text,
  transaction_date text,
  account_number text,
  sub_account text,
  code text,
  content text,
  transfer_type text,
  transfer_amount bigint,
  accumulated bigint,
  reference_code text,
  description text,
  -- Đơn hàng khớp được (nếu có)
  order_id uuid references public.orders (id),
  created_at timestamptz not null default now()
);

alter table public.sepay_transactions enable row level security;
-- Không tạo policy public — chỉ webhook (service role) được ghi.
