import {
  Rocket,
  Building2,
  ShoppingCart,
  CalendarClock,
  LayoutDashboard,
  Users,
  Globe,
  Wallet,
  Sparkles,
  Zap,
  ShieldCheck,
  Clock,
  MessageSquare,
  Wand2,
  CheckCircle2,
  UploadCloud,
  Store,
  Scissors,
  Briefcase,
  Megaphone,
  GraduationCap,
  TrendingUp,
  Gift,
  FileText,
  Palette,
  LifeBuoy,
  Code2,
  Lock,
  HelpCircle,
  Coins,
  Target,
  Layers,
  Compass,
} from "lucide-react";
import type { IconName, LucideIcon } from "@/types";

/** Registry ánh xạ IconName -> component icon, giúp config chỉ lưu data thuần. */
export const iconMap: Record<IconName, LucideIcon> = {
  rocket: Rocket,
  building: Building2,
  cart: ShoppingCart,
  calendar: CalendarClock,
  dashboard: LayoutDashboard,
  users: Users,
  globe: Globe,
  wallet: Wallet,
  sparkles: Sparkles,
  zap: Zap,
  shield: ShieldCheck,
  clock: Clock,
  message: MessageSquare,
  wand: Wand2,
  check: CheckCircle2,
  upload: UploadCloud,
  store: Store,
  scissors: Scissors,
  briefcase: Briefcase,
  megaphone: Megaphone,
  graduation: GraduationCap,
  trending: TrendingUp,
  gift: Gift,
  file: FileText,
  palette: Palette,
  lifebuoy: LifeBuoy,
  code: Code2,
  lock: Lock,
  help: HelpCircle,
  coins: Coins,
  target: Target,
  layers: Layers,
  compass: Compass,
};

export function getIcon(name: IconName): LucideIcon {
  return iconMap[name];
}
